### ISSUE TITLE
Routing error in prod :(

### ISSUE THREAD

**Issue by bfosberry** [beanieboi/docker-than-light#39]
I borked it!

ActionController::RoutingError (uninitialized constant Application::ShipsController)

Unsure why this is happening, not doing anything weird with the ships controller that was not done with the dashboards controller. 

```
2016-03-23T02:38:58.602152+00:00 app[web.1]: Started POST "/ships" for 72.182.15.101 at 2016-03-23 02:38:58 +0000
2016-03-23T02:38:58.604961+00:00 app[web.1]: 
2016-03-23T02:38:58.604971+00:00 app[web.1]: ActionController::RoutingError (uninitialized constant Application::ShipsController):
2016-03-23T02:38:58.604972+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:263:in `const_get'
2016-03-23T02:38:58.604973+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:263:in `block in constantize'
2016-03-23T02:38:58.604974+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in `each'
2016-03-23T02:38:58.604975+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in `inject'
2016-03-23T02:38:58.604976+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in `constantize'
2016-03-23T02:38:58.604977+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:70:in `controller_reference'
2016-03-23T02:38:58.604977+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:60:in `controller'
2016-03-23T02:38:58.604978+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:39:in `serve'
2016-03-23T02:38:58.604979+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:43:in `block in serve'
2016-03-23T02:38:58.604980+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in `each'
2016-03-23T02:38:58.604980+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in `serve'
2016-03-23T02:38:58.604981+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:817:in `call'
2016-03-23T02:38:58.604982+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
2016-03-23T02:38:58.604983+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
2016-03-23T02:38:58.604984+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/builder.rb:63:in `call'
2016-03-23T02:38:58.604985+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
2016-03-23T02:38:58.604985+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
2016-03-23T02:38:58.604986+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
2016-03-23T02:38:58.604987+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
2016-03-23T02:38:58.604988+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/flash.rb:260:in `call'
2016-03-23T02:38:58.604988+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
2016-03-23T02:38:58.604989+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
2016-03-23T02:38:58.604990+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/cookies.rb:560:in `call'
2016-03-23T02:38:58.604990+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/query_cache.rb:36:in `call'
2016-03-23T02:38:58.604992+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
2016-03-23T02:38:58.604992+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
2016-03-23T02:38:58.604993+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
2016-03-23T02:38:58.604994+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
2016-03-23T02:38:58.604994+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
2016-03-23T02:38:58.604995+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
2016-03-23T02:38:58.604996+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
2016-03-23T02:38:58.604996+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
2016-03-23T02:38:58.604997+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
2016-03-23T02:38:58.604998+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:38:in `call_app'
2016-03-23T02:38:58.604999+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `block in call'
2016-03-23T02:38:58.604999+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `block in tagged'
2016-03-23T02:38:58.605000+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:26:in `tagged'
2016-03-23T02:38:58.605001+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `tagged'
2016-03-23T02:38:58.605001+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `call'
2016-03-23T02:38:58.605006+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'
2016-03-23T02:38:58.605006+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
2016-03-23T02:38:58.605007+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
2016-03-23T02:38:58.605008+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
2016-03-23T02:38:58.605008+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/static.rb:120:in `call'
2016-03-23T02:38:58.605009+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
2016-03-23T02:38:58.605010+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/ssl.rb:24:in `call'
2016-03-23T02:38:58.605010+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:518:in `call'
2016-03-23T02:38:58.605011+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:165:in `call'
2016-03-23T02:38:58.605012+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/puma-3.1.1/lib/puma/configuration.rb:227:in `call'
2016-03-23T02:38:58.605013+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/puma-3.1.1/lib/puma/server.rb:561:in `handle_request'
2016-03-23T02:38:58.605013+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/puma-3.1.1/lib/puma/server.rb:406:in `process_client'
2016-03-23T02:38:58.605014+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/puma-3.1.1/lib/puma/server.rb:271:in `block in run'
2016-03-23T02:38:58.605015+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/puma-3.1.1/lib/puma/thread_pool.rb:111:in `block in spawn_thread'
2016-03-23T02:38:58.605016+00:00 app[web.1]: 
2016-03-23T02:38:58.605016+00:00 app[web.1]: 
```

**Comment by beanieboi** [comment]
you changed that in the previous PR #38. there is no ShipsController but you are referencing it.

**Comment by bfosberry** [comment]
Ooh I forgot to add it to git, ty

**Comment by bfosberry** [comment]
Added, working ok now ty
